### PR TITLE
Remove glacier endpoint - again

### LINKED ISSUE #296: Consider removing Glacier endpoint?
Unclear if this is integrated anywhere / if it's relevant in this tool.

### PR DESCRIPTION
**Pull request by Joshdpaul**
This PR closes #296  by deleting `glacier.py` and `glacier.html` files entirely, removing the glacier import from `routes/__init__.py`, and by removing all references to the glaciology data from `index.html` and the `README.md`.

To test, run the `flask` application as described in `README.md`, and verify that the glaciology data is no longer referenced on the API index page and that a previously existing glacier endpoint (eg, http://localhost:5000/glacier/60/-144) now returns no data.

### CODE REVIEW

**Comment by charparr** [comment]
Take a look in `postprocessing.py`, I think you can remove this line:
https://github.com/ua-snap/data-api/blob/f1744be4827c06e7676c04d1eb6336c0dad9e879/postprocessing.py#L27

**Comment by charparr** [comment]
Oh this one too!
https://github.com/ua-snap/data-api/blob/f1744be4827c06e7676c04d1eb6336c0dad9e879/postprocessing.py#L23

**Comment by Joshdpaul** [comment]
The 2 comments above were addressed by [5d7ed08](https://github.com/ua-snap/data-api/pull/347/commits/5d7ed08afd6b8bfaf64966f2445b917e1e62712c)

**Comment by charparr** [comment]
Great! This PR removes all references to the now-deprecated glacier endpoint from the API.

**Pull request merged**
