### PR TITLE
Explicit argument validation

### LINKED ISSUE #337: Bad ?arg=value requests still give data
For example, see the `fetch_mmm_point_data()` function in  `taspr.py`. The script checks for a `?summarize=mmm` argument via `if request.args.get("summarize") == "mmm":` condition. However any typo in this argument (or any argument at all for that matter) will default this condition to return 'None' in which case the script moves to the `else:` condition and continues to execute.

For example, the endpoints below with bad arguments all return data, but should probably return an error instead to avoid confusion:

http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summarize=max
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summarize=mmmm
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?summary=mmm
http://127.0.0.1:5001/temperature/65.0628/-146.1627/1940/2060?foo=bar

Consider using a zero-length argument dictionary check first, eg:

`if len(request.args) == 0:  
     return "default endpoint"`

then check for arguments explicitly, eg: 

`elif: "summarize" in request.args:  
        if request.args.get("summarize") == "mmm":  
                 summarize the data  
        else: throw an error`

### PR DESCRIPTION
**Pull request by Joshdpaul**
This PR addresses closes #337 by using endpoint-specific if/then routines to validate arguments. Below is a comprehensive list of requests to test for each affected endpoint. Feel free to pick and choose / create new requests of your own for testing. (Side note, I originally thought the hydrology endpoint would need this treatment, but it looks like it was already done in previous work.)

Is this too much extra code? I have a feeling that the conditional statements could be written more succinctly / efficiently, 
so if you see any obvious areas for improvement / code-trimming please advise!

**TO TEST:** 

Click the links below and confirm expected behavior. Or, create your own requests. It might also be helpful to have a browser open with the production version of the API to compare the returns. In my experience, all the requests below in the "400 club" currently return data in the production version. 

# **degree days:**
these should work:
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summarize=mmm
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summarize=mmm&format=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summarize=mmm
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?format=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summarize=mmm&format=csv

these should return 400:
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summarize=mm
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summary=mmm 
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summarize=mm&format=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627?summarize=mmm&format=cs
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summarize=mm
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summary=mmm 
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?forma=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?format=cs
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summarize=mm&format=csv
http://127.0.0.1:5000/degree_days/heating/65.0628/-146.1627/1990/2080?summarize=mmm&format=cs

# **snow**:
these should work:
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?summarize=mmm
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?format=csv

these should return 400:
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?summarize=mm
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?summary=mmm
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?forma=csv
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?format=cs

# **taspr**:
these should work:
http://127.0.0.1:5000/temperature/point/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/precipitation/point/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/taspr/point/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/temperature/area/19010208?format=csv
http://127.0.0.1:5000/precipitation/area/19010208?format=csv
http://127.0.0.1:5000/taspr/area/19010208?format=csv
http://127.0.0.1:5000/precipitation/frequency/point/65.028/-146.1627?format=csv
http://127.0.0.1:5000/temperature/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summarize=mmm
http://127.0.0.1:5000/precipitation/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/precipitation/65.0628/-146.1627?summarize=mmm
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627?format=csv
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627?summarize=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?format=csv
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summarize=mmm
http://127.0.0.1:5000/precipitation/65.0628/-146.1627/1940/2060?format=csv
http://127.0.0.1:5000/precipitation/65.0628/-146.1627/1940/2060?summarize=mmm
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627/1940/2060?format=csv
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627/1940/2060?summarize=mmm

these should return 400:
http://127.0.0.1:5000/temperature/point/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/temperature/point/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/precipitation/point/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/precipitation/point/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/taspr/point/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/taspr/point/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/temperature/area/19010208?forma=csv
http://127.0.0.1:5000/temperature/area/19010208?format=cs
http://127.0.0.1:5000/precipitation/area/19010208?forma=csv
http://127.0.0.1:5000/precipitation/area/19010208?format=cs
http://127.0.0.1:5000/taspr/area/19010208?forma=csv
http://127.0.0.1:5000/taspr/area/19010208?format=cs
http://127.0.0.1:5000/precipitation/frequency/point/65.028/-146.1627?forma=csv
http://127.0.0.1:5000/precipitation/frequency/point/65.028/-146.1627?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/temperature/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summarize=mm
http://127.0.0.1:5000/precipitation/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/precipitation/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summarize=mm
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627?forma=csv
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627?summarize=mm
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?forma=csv
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summarize=mm
http://127.0.0.1:5000/precipitation/65.0628/-146.1627/1940/2060?forma=csv
http://127.0.0.1:5000/precipitation/65.0628/-146.1627/1940/2060?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summarize=mm
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627/1940/2060?forma=csv
http://127.0.0.1:5000/temperature/jan/65.0628/-146.1627/1940/2060?format=cs
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summary=mmm
http://127.0.0.1:5000/temperature/65.0628/-146.1627/1940/2060?summarize=mm

### CODE REVIEW

**Review by cstephen — CHANGES_REQUESTED** [review]
I tested all of the example good & bad URLs, and almost everything looks great!

For some reason these two URLs return HTTP 400 / "Bad request" errors:

http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?summarize=mmm
http://127.0.0.1:5000/snow/snowfallequivalent/61.5/-147?format=csv

Also, after talking this over with Bruce, I added some basic app-wide validation with marshmallow that will catch invalid GET parameters & values. However, all of the logic you have implemented here to determine what to do with the GET parameters & values still applies. Think of this as just an extra layer of security. Anything marked as invalid with marshmallow will return an HTTP 422 error, and a new "Invalid GET parameter..." template.

**Comment by Joshdpaul** [comment]
OK @cstephen , I was able to remove a bunch of extraneous code in the routes themselves, and making the route-specific argument validation a little more standardized. I also revised the hydrology route using the same logic.

I checked the links in the comments above (including the two you pointed out) and everything seems to be in order. Except, the only problem I have is in chaining the summarize and format arguments in the hydrology endpoint...

This URL produces a `127.0.0.1` response for me, even though the individual `?summarize=mmm` and `?format=csv` arguments work as expected. The production version of the API does not have this issue, so I don't know what I am doing wrong here? What response do you get here?

http://127.0.0.1:5000/hydrology/point/61.5/-147?summarize=mmm&format=csv

Other than that, I think we are pretty close here!

**Comment by cstephen** [comment]
I think this PR is good to go now. I've made the following changes:

- I've added support for the `community` GET parameter that is used to optionally add a community name to the CSV filename and metadata. I had forgotten about this previously. Support for this has been added to the "before request" marshmallow validation and the routes that have code to support it.
- http://127.0.0.1:5000/hydrology/point/61.5/-147?summarize=mmm&format=csv has been fixed. This bug is present in the data-api `main` branch too. It turns out it has to do with CSV filenames with commas in them. In this case, it was the "Minimum, Mean, and Maximum Across All Decades 1950-2099" part of the hydrology CSV filename causing the issue. I've fixed this by running entire CSV filename through the `quote()` function, not just the community name. This issue is browser-specific, which is probably how it crept into the `main` branch originally.
- CSV previews for degree-days-based items have been fixed. See 97ee9f4ddb9221d33c24edb9895833ff78375f38.

I've confirmed that all example URLs in the original PR description continue to work (or not work) as expected, and here are some additional URLs confirmed to work after my last few commits:

http://127.0.0.1:5000/hydrology/point/61.5/-147?summarize=mmm&format=csv
http://localhost:5000/temperature/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/indicators/base/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/precipitation/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/hydrology/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/permafrost/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/alfresco/flammability/local/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/alfresco/veg_type/local/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/beetles/point/63.3917/-148.951?format=csv&community=AK50
http://localhost:5000/demographics/AK50?format=csv

Things are looking really nice and the code looks much cleaner!

I'm marking this PR as approved, but please take a another look at this to make sure things are working as expected on your end, @Joshdpaul. 🏈 Feel free to merge if so!

**Review by cstephen — APPROVED** [review]

**Comment by cstephen** [comment]
I think this is good to merge again now, @Joshdpaul, after resolving merge conflicts with `main` + my last couple commits.

**Pull request merged**
